### PR TITLE
fix: remove stylistic rules

### LINKED ISSUE #6: Style rules are not disabled
This config is not supposed to include any stylistic or subjective rules, however there are various sytlistic rules that do not appear to be disabled (even though there's a comment suggesting they should be): [preact stylistic rules](https://github.com/preactjs/eslint-config-preact/blob/6687c4931b3df7d52cdf6fca98a20d2093eb81de/index.js#L93) and [general javascript stylistic rules](https://github.com/preactjs/eslint-config-preact/blob/6687c4931b3df7d52cdf6fca98a20d2093eb81de/index.js#L151).

### PR DESCRIPTION
**Pull request by imgalli**
Carries out @ethanwu10's change to remove stylistic rules.

Fixes #6

### CODE REVIEW

**Review by marvinhagemeister — APPROVED** [review]
Awesome thanks a bunch for the PR 👍

**Comment by imgalli** [comment]
Any chance of a release please? 😄

**Comment by marvinhagemeister** [comment]
Published as `1.1.4` 🚀

**Comment by imgalli** [comment]
Thank you very much!

**Pull request merged**
